name: Update Telegram Feed

permissions:
  contents: write
  
on:
  schedule:
    - cron: '*/11 * * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

   # - name: Show HTML
     # run: python -c "import requests; print(requests.get('https://t.me/s/VahidOnline').text[:2000])"
      
    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
      
        # 1. Always sync FIRST
        git fetch origin main
        git reset --hard origin/main
      
        # 2. Run script AFTER clean state
        python scraper.py
      
        # 3. Commit changes
        git add README.md
        git commit -m "update" || echo "no changes"
      
        # 4. Push safely
        git push
